# Generated by Django 5.1.3 on 2024-11-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "first_name",
                    models.CharField(
                        help_text="Enter the person's first name (or first initial if their full first name is             unknown)",
                        max_length=50,
                    ),
                ),
                (
                    "middle_initial",
                    models.CharField(
                        blank=True,
                        help_text="Enter the person's middle initial, if they have one or if it is known",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Enter the person's last name", max_length=50
                    ),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True,
                        help_text="Enter the person's suffix, if they have one",
                        max_length=5,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "People",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
