# Generated by Django 5.1.3 on 2025-01-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specimens", "0002_specimenrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specimenrecord",
            name="temperature",
            field=models.CharField(
                blank=True,
                help_text="Enter the temperature (F) during the specimen's collection if outdoors",
                max_length=10,
                null=True,
            ),
        ),
    ]
