# Generated by Django 5.1.3 on 2025-01-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specimens", "0003_alter_specimenrecord_temperature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specimenrecord",
            name="temperature",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Enter the temperature (F) during the specimen's collection if outdoors",
                max_length=10,
            ),
        ),
    ]
