# Generated by Django 6.0.1 on 2026-01-21 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0012_alter_county_state_alter_gps_locality_and_more"),
        ("specimens", "0004_alter_specimenrecord_temperature"),
        ("taxonomy", "0016_alter_family_order_alter_genus_tribe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specimenrecord",
            name="collecting_trip",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the collecting trip on which the specimen was collected",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="specimen_records",
                to="geography.collectingtrip",
            ),
        ),
        migrations.AlterField(
            model_name="specimenrecord",
            name="country",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the country in which the specimen was collected",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="specimen_records",
                to="geography.country",
            ),
        ),
        migrations.AlterField(
            model_name="specimenrecord",
            name="county",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the county in which the specimen was collected",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="specimen_records",
                to="geography.county",
            ),
        ),
        migrations.AlterField(
            model_name="specimenrecord",
            name="determiner",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the person who determined the specimen",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="specimen_determiners",
                to="specimens.person",
            ),
        ),
        migrations.AlterField(
            model_name="specimenrecord",
            name="family",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the specimen's family (if known)",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="taxonomy.family",
            ),
        ),
        migrations.AlterField(
            model_name="specimenrecord",
            name="genus",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the specimen's genus (if known)",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="taxonomy.genus",
            ),
        ),
        migrations.AlterField(
            model_name="specimenrecord",
            name="gps",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the GPS coordinates at which the specimen was collected",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="specimen_records",
                to="geography.gps",
            ),
        ),
        migrations.AlterField(
            model_name="specimenrecord",
            name="locality",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the locality at which the specimen was collected",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="specimen_records",
                to="geography.locality",
            ),
        ),
        migrations.AlterField(
            model_name="specimenrecord",
            name="order",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the specimen's order (if known)",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="taxonomy.order",
            ),
        ),
        migrations.AlterField(
            model_name="specimenrecord",
            name="preparer",
            field=models.ForeignKey(
                help_text="Select the person who prepared the specimen",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="specimen_preparers",
                to="specimens.person",
            ),
        ),
        migrations.AlterField(
            model_name="specimenrecord",
            name="species",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the specimen's species (if known)",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="taxonomy.species",
            ),
        ),
        migrations.AlterField(
            model_name="specimenrecord",
            name="state",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the state in which the specimen was collected",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="specimen_records",
                to="geography.state",
            ),
        ),
        migrations.AlterField(
            model_name="specimenrecord",
            name="subfamily",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the specimen's subfamily (if known)",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="taxonomy.subfamily",
            ),
        ),
        migrations.AlterField(
            model_name="specimenrecord",
            name="subspecies",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the specimen's subspecies (if known)",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="taxonomy.subspecies",
            ),
        ),
        migrations.AlterField(
            model_name="specimenrecord",
            name="tribe",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the specimen's tribe (if known)",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="taxonomy.tribe",
            ),
        ),
    ]
