# Generated by Django 5.1.3 on 2024-11-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the taxon's scientific name", max_length=100
                    ),
                ),
                (
                    "common_name",
                    models.CharField(
                        blank=True,
                        help_text="Enter the taxon's common name, if it has one",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        help_text="Enter the taxon's authority", max_length=100
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
