# Generated by Django 5.1.3 on 2024-11-17 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0004_tribe"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="family",
            options={"verbose_name_plural": "Families"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={},
        ),
        migrations.AlterModelOptions(
            name="subfamily",
            options={"verbose_name_plural": "Subfamilies"},
        ),
        migrations.AlterModelOptions(
            name="tribe",
            options={},
        ),
        migrations.CreateModel(
            name="Genus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the taxon's scientific name", max_length=100
                    ),
                ),
                (
                    "common_name",
                    models.CharField(
                        blank=True,
                        help_text="Enter the taxon's common name, if it has one",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        help_text="Enter the taxon's authority", max_length=100
                    ),
                ),
                (
                    "tribe",
                    models.ForeignKey(
                        help_text="Select a tribe to which this genus belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="taxonomy.tribe",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Genera",
            },
        ),
    ]
