# Generated by Django 5.1.3 on 2024-11-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0006_species"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="species",
            options={"ordering": ["genus"], "verbose_name_plural": "Species"},
        ),
        migrations.AddField(
            model_name="species",
            name="mona",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Enter the MONA (Hodges) number for the species (Lepidoptera only)",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="p3",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Enter the P3 (Pohl, Patterson, Pelham 2016) number for the species (Lepidoptera only)",
                max_digits=8,
                null=True,
            ),
        ),
    ]
