# Generated by Django 5.1.3 on 2024-11-17 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0007_alter_species_options_species_mona_species_p3"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="species",
            options={"ordering": ["genus", "name"], "verbose_name_plural": "Species"},
        ),
        migrations.AlterField(
            model_name="genus",
            name="tribe",
            field=models.ForeignKey(
                help_text="Select the tribe to which this genus belongs",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="taxonomy.tribe",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="genus",
            field=models.ForeignKey(
                help_text="Select the genus to which this species belongs",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="taxonomy.genus",
            ),
        ),
        migrations.AlterField(
            model_name="subfamily",
            name="family",
            field=models.ForeignKey(
                help_text="Select the family to which this subfamily belongs",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="taxonomy.family",
            ),
        ),
        migrations.AlterField(
            model_name="tribe",
            name="subfamily",
            field=models.ForeignKey(
                help_text="Select the subfamily to which this tribe belongs",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="taxonomy.subfamily",
            ),
        ),
        migrations.CreateModel(
            name="Subspecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the taxon's scientific name", max_length=100
                    ),
                ),
                (
                    "common_name",
                    models.CharField(
                        blank=True,
                        help_text="Enter the taxon's common name, if it has one",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        help_text="Enter the taxon's authority", max_length=100
                    ),
                ),
                (
                    "mona",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Enter the MONA (Hodges) number for the subspecies (Lepidoptera only). If it lacks its own MONA number, use the nominate species' number",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "p3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Enter the P3 (Pohl, Patterson, Pelham 2016) number for the species (Lepidoptera only). If it lacks its own P3 number, use the nominate species' number.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        help_text="Select the species to which this subspecies belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="taxonomy.species",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Subspecies",
                "ordering": ["species", "name"],
            },
        ),
    ]
