# Generated by Django 5.1.3 on 2024-11-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0008_alter_species_options_alter_genus_tribe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="p3",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Enter the P3 (Pohl, Patterson, Pelham 2016) number for the species (Lepidoptera             only)",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subspecies",
            name="mona",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Enter the MONA (Hodges) number for the subspecies (Lepidoptera only). If it             lacks its own MONA number, use the nominate species' number",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subspecies",
            name="p3",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Enter the P3 (Pohl, Patterson, Pelham 2016) number for the species (Lepidoptera             only). If it lacks its own P3 number, use the nominate species' number.",
                max_digits=8,
                null=True,
            ),
        ),
    ]
