# Generated by Django 5.1.3 on 2024-11-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0009_alter_species_p3_alter_subspecies_mona_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="mona",
            field=models.CharField(
                blank=True,
                help_text="Enter the MONA (Hodges) number for the species (Lepidoptera only)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="p3",
            field=models.CharField(
                blank=True,
                help_text="Enter the P3 (Pohl, Patterson, Pelham 2016) number for the species (Lepidoptera             only)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subspecies",
            name="mona",
            field=models.CharField(
                blank=True,
                help_text="Enter the MONA (Hodges) number for the subspecies (Lepidoptera only). If it             lacks its own MONA number, use the nominate species' number",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subspecies",
            name="p3",
            field=models.CharField(
                blank=True,
                help_text="Enter the P3 (Pohl, Patterson, Pelham 2016) number for the species (Lepidoptera             only). If it lacks its own P3 number, use the nominate species' number.",
                null=True,
            ),
        ),
    ]
