# Generated by Django 5.1.3 on 2025-01-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0010_alter_species_mona_alter_species_p3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="ps",
            field=models.CharField(
                blank=True,
                help_text="Enter the Phylogenetic Sequence (Pohl and Nanz, 2023) number for the species             (Lepidoptera only)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subspecies",
            name="ps",
            field=models.CharField(
                blank=True,
                help_text="Enter the Phylogenetic Sequence (Pohl and Nanz, 2023) number for the subspecies             (Lepidoptera only). If it lacks its own Phylogenetic Sequence number, use the             nominate species' number",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subspecies",
            name="p3",
            field=models.CharField(
                blank=True,
                help_text="Enter the P3 (Pohl, Patterson, Pelham 2016) number for the subspecies             (Lepidoptera only). If it lacks its own P3 number, use the nominate species' number",
                null=True,
            ),
        ),
    ]
