# Generated by Django 5.1.3 on 2025-01-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0011_species_ps_subspecies_ps_alter_subspecies_p3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subspecies",
            name="mona",
            field=models.CharField(
                blank=True,
                help_text="Enter the MONA (Hodges) number for the subspecies (Lepidoptera only). If it             lacks its own MONA number, use the nominate species' number",
                null=True,
                verbose_name="MONA #",
            ),
        ),
        migrations.AlterField(
            model_name="subspecies",
            name="p3",
            field=models.CharField(
                blank=True,
                help_text="Enter the P3 (Pohl, Patterson, Pelham 2016) number for the subspecies             (Lepidoptera only). If it lacks its own P3 number, use the nominate species' number",
                null=True,
                verbose_name="P3 #",
            ),
        ),
        migrations.AlterField(
            model_name="subspecies",
            name="ps",
            field=models.CharField(
                blank=True,
                help_text="Enter the Phylogenetic Sequence (Pohl and Nanz, 2023) number for the subspecies             (Lepidoptera only). If it lacks its own Phylogenetic Sequence number, use the             nominate species' number",
                null=True,
                verbose_name="PS #",
            ),
        ),
    ]
