# Generated by Django 5.1.3 on 2025-01-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0012_alter_subspecies_mona_alter_subspecies_p3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="mona",
            field=models.CharField(
                blank=True,
                help_text="Enter the MONA (Hodges) number for the species (Lepidoptera only)",
                null=True,
                verbose_name="MONA #",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="p3",
            field=models.CharField(
                blank=True,
                help_text="Enter the P3 (Pohl, Patterson, Pelham 2016) number for the species (Lepidoptera             only)",
                null=True,
                verbose_name="P3 #",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="ps",
            field=models.CharField(
                blank=True,
                help_text="Enter the Phylogenetic Sequence (Pohl and Nanz, 2023) number for the species             (Lepidoptera only)",
                null=True,
                verbose_name="PS #",
            ),
        ),
    ]
