# Generated by Django 5.1.10 on 2025-06-07 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0013_alter_species_mona_alter_species_p3_alter_species_ps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subspecies",
            name="species",
            field=models.ForeignKey(
                help_text="Select the species to which this subspecies belongs",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subspecies",
                to="taxonomy.species",
            ),
        ),
    ]
