# Generated by Django 5.1.15 on 2026-01-10 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0014_alter_subspecies_species"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="family",
            options={"ordering": ["name", "order"], "verbose_name_plural": "Families"},
        ),
        migrations.AlterModelOptions(
            name="genus",
            options={"ordering": ["name", "tribe"], "verbose_name_plural": "Genera"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="subfamily",
            options={
                "ordering": ["name", "family"],
                "verbose_name_plural": "Subfamilies",
            },
        ),
        migrations.AlterModelOptions(
            name="tribe",
            options={"ordering": ["name", "subfamily"]},
        ),
    ]
