# Generated by Django 6.0.1 on 2026-01-21 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0015_alter_family_options_alter_genus_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="family",
            name="order",
            field=models.ForeignKey(
                help_text="Select an order to which this family belongs",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="taxonomy.order",
            ),
        ),
        migrations.AlterField(
            model_name="genus",
            name="tribe",
            field=models.ForeignKey(
                help_text="Select the tribe to which this genus belongs",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="taxonomy.tribe",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="genus",
            field=models.ForeignKey(
                help_text="Select the genus to which this species belongs",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="taxonomy.genus",
            ),
        ),
        migrations.AlterField(
            model_name="subfamily",
            name="family",
            field=models.ForeignKey(
                help_text="Select the family to which this subfamily belongs",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="taxonomy.family",
            ),
        ),
        migrations.AlterField(
            model_name="subspecies",
            name="species",
            field=models.ForeignKey(
                help_text="Select the species to which this subspecies belongs",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="subspecies",
                to="taxonomy.species",
            ),
        ),
        migrations.AlterField(
            model_name="tribe",
            name="subfamily",
            field=models.ForeignKey(
                help_text="Select the subfamily to which this tribe belongs",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="taxonomy.subfamily",
            ),
        ),
    ]
