# Generated by Django 5.1.10 on 2025-06-07 17:46

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taxonomy", "0013_alter_species_mona_alter_species_p3_alter_species_ps"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeciesPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "taxonomy",
                    wagtail.fields.RichTextField(
                        blank=True, default="", help_text="Enter taxonomy details"
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True, default="", help_text="Enter species description"
                    ),
                ),
                (
                    "distribution",
                    wagtail.fields.RichTextField(
                        blank=True, default="", help_text="Enter distribution details"
                    ),
                ),
                (
                    "seasonality",
                    wagtail.fields.RichTextField(
                        blank=True, default="", help_text="Enter seasonality details"
                    ),
                ),
                (
                    "habitat",
                    wagtail.fields.RichTextField(
                        blank=True, default="", help_text="Enter the species' habitat"
                    ),
                ),
                (
                    "food",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="",
                        help_text="Enter info larval and adult food sources",
                    ),
                ),
                (
                    "life_cycle",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="",
                        help_text="Enter details about the life cycle",
                    ),
                ),
                (
                    "species",
                    models.OneToOneField(
                        help_text="Select the species this page is about",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species_page",
                        to="taxonomy.species",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
