# Generated by Django 5.1.10 on 2025-06-07 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
        ("taxonomy", "0013_alter_species_mona_alter_species_p3_alter_species_ps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speciespage",
            name="species",
            field=models.OneToOneField(
                help_text="Select the species this page is about",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="species_page",
                to="taxonomy.species",
            ),
        ),
    ]
