# Generated by Django 5.1.3 on 2024-11-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="abbr",
            field=models.CharField(
                help_text="Enter the country's 3-letter abbreviation", max_length=3
            ),
        ),
    ]
