# Generated by Django 5.1.3 on 2024-11-12 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0002_alter_country_abbr"),
    ]

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the name of the state (or province)",
                        max_length=50,
                    ),
                ),
                (
                    "abbr",
                    models.CharField(
                        help_text="Enter the state's (or province's) abbreviation (should be 2 letters)",
                        max_length=10,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="Select the state's country",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="geography.country",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
