# Generated by Django 5.1.3 on 2024-11-12 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0003_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="County",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the name of the county (or parish)",
                        max_length=50,
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        help_text="Select the state to which this county (or parish) belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="geography.state",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Counties",
                "ordering": ["name"],
            },
        ),
    ]
