# Generated by Django 5.1.3 on 2024-11-12 18:32

import geography.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0004_county"),
    ]

    operations = [
        migrations.CreateModel(
            name="Locality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    wagtail.fields.StreamField(
                        [("Country", 0), ("State", 1), ("County", 2)],
                        block_lookup={
                            0: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                (geography.models.Country,),
                                {},
                            ),
                            1: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                (geography.models.State,),
                                {},
                            ),
                            2: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                (geography.models.County,),
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Enter a locality's name, if it has one",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "range",
                    models.CharField(
                        blank=True,
                        help_text="Enter the distance and direction of this locality from the nearest town (e.g., 2 km NW), if known",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "town",
                    models.CharField(
                        blank=True,
                        help_text="Enter the nearest town, if known",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Localities",
                "ordering": ["name", "town"],
            },
        ),
    ]
