# Generated by Django 5.1.3 on 2024-11-14 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0005_locality"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locality",
            name="region",
        ),
        migrations.AddField(
            model_name="locality",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="geography.country",
            ),
        ),
        migrations.AddField(
            model_name="locality",
            name="county",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="geography.county",
            ),
        ),
        migrations.AddField(
            model_name="locality",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="geography.state",
            ),
        ),
    ]
