# Generated by Django 5.1.3 on 2024-11-15 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0006_remove_locality_region_locality_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locality",
            name="range",
            field=models.CharField(
                blank=True,
                help_text="Enter the distance and direction of this locality from the nearest town (e.g.,             2 km NW), if known",
                max_length=10,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="GPS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Enter the latitude in decimal degrees",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Enter the longitude in decimal degrees",
                        max_digits=11,
                        null=True,
                    ),
                ),
                (
                    "elevation",
                    models.CharField(
                        help_text="Enter the elevation in meters", max_length=15
                    ),
                ),
                (
                    "locality",
                    models.ForeignKey(
                        help_text="Select the locality for this set of coordinates",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="geography.locality",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "GPS coordinates",
                "ordering": ["latitude", "longitude"],
            },
        ),
    ]
