# Generated by Django 5.1.3 on 2024-11-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0007_alter_locality_range_gps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gps",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Enter the latitude in decimal degrees",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="gps",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Enter the longitude in decimal degrees",
                max_digits=9,
                null=True,
            ),
        ),
    ]
