# Generated by Django 5.1.3 on 2024-11-15 03:50

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0008_alter_gps_latitude_alter_gps_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectingTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Enter a name for the trip", max_length=50
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "notes",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Enter notes about the trip", null=True
                    ),
                ),
                (
                    "states",
                    models.ManyToManyField(
                        help_text="Select the state(s) visited during the trip",
                        related_name="collecting_trips",
                        to="geography.state",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
