# Generated by Django 5.1.3 on 2024-11-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0009_collectingtrip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectingtrip",
            name="states",
            field=models.ManyToManyField(
                help_text="Select the state(s) visited during the trip (hold down Command to select             multiple states)",
                related_name="collecting_trips",
                to="geography.state",
            ),
        ),
    ]
