# Generated by Django 5.1.3 on 2024-11-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0010_alter_collectingtrip_states"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gps",
            name="latitude",
            field=models.CharField(
                blank=True, help_text="Enter the latitude in decimal degrees", null=True
            ),
        ),
        migrations.AlterField(
            model_name="gps",
            name="longitude",
            field=models.CharField(
                blank=True,
                help_text="Enter the longitude in decimal degrees",
                null=True,
            ),
        ),
    ]
