# Generated by Django 6.0.1 on 2026-01-21 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0011_alter_gps_latitude_alter_gps_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="county",
            name="state",
            field=models.ForeignKey(
                help_text="Select the state to which this county (or parish) belongs",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="geography.state",
            ),
        ),
        migrations.AlterField(
            model_name="gps",
            name="locality",
            field=models.ForeignKey(
                help_text="Select the locality for this set of coordinates",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="geography.locality",
            ),
        ),
        migrations.AlterField(
            model_name="locality",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="geography.country",
            ),
        ),
        migrations.AlterField(
            model_name="locality",
            name="county",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="geography.county",
            ),
        ),
        migrations.AlterField(
            model_name="locality",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="geography.state",
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="country",
            field=models.ForeignKey(
                help_text="Select the state's country",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="geography.country",
            ),
        ),
    ]
