# Generated by Django 5.1.5 on 2025-01-29 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0011_alter_gps_latitude_alter_gps_longitude"),
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customimage",
            name="caption",
        ),
        migrations.CreateModel(
            name="BaseLiveImage",
            fields=[
                (
                    "customimage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="images.customimage",
                    ),
                ),
                (
                    "collecting_trip",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select the collecting trip during which the image was taken",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="geography.collectingtrip",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select the country in which the image was taken",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="geography.country",
                    ),
                ),
                (
                    "county",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select the county in which the image was taken",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="geography.county",
                    ),
                ),
                (
                    "gps",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select the GPS coordinates at which the image was taken",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="geography.gps",
                    ),
                ),
                (
                    "locality",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select the locality at which the image was taken",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="geography.locality",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select the state in which the image was taken",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="geography.state",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("images.customimage",),
        ),
    ]
