# Generated by Django 5.1.10 on 2025-06-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_customimage_date_customimage_notes_habitatimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customimage",
            name="date",
            field=models.DateField(help_text="Enter the date the image was taken"),
        ),
    ]
