# Generated by Django 5.1.10 on 2025-06-08 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0004_alter_customimage_date"),
        ("specimens", "0004_alter_specimenrecord_temperature"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecimenRecordImage",
            fields=[
                (
                    "customimage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="images.customimage",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("dorsal", "dorsal"),
                            ("ventral", "ventral"),
                            ("lateral", "lateral"),
                        ],
                        default="dorsal",
                        help_text="Select the view of the specimen in the image",
                        max_length=10,
                    ),
                ),
                (
                    "usi",
                    models.ForeignKey(
                        help_text="Select the specimen in the image",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specimen_images",
                        to="specimens.specimenrecord",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("images.customimage",),
        ),
    ]
