# Generated by Django 5.1.10 on 2025-06-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0005_specimenrecordimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="insectimage",
            name="featured_family",
            field=models.BooleanField(
                default=False,
                help_text="Toggle to make this image represent the family to which the insect in the image belongs",
            ),
        ),
        migrations.AddField(
            model_name="insectimage",
            name="featured_species",
            field=models.BooleanField(
                default=False,
                help_text="Toggle to make this image represent the species to which the insect in the image belongs",
            ),
        ),
    ]
