# Generated by Django 5.1.10 on 2025-06-12 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0006_insectimage_featured_family_and_more"),
        ("pages", "0002_alter_speciespage_species"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insectimage",
            name="featured_family",
            field=models.BooleanField(
                default=False,
                help_text="Toggle to make this image represent the family to which the insect in the image                   belongs",
            ),
        ),
        migrations.AlterField(
            model_name="insectimage",
            name="featured_species",
            field=models.BooleanField(
                default=False,
                help_text="Toggle to make this image represent the species to which the insect in the                   image belongs",
            ),
        ),
        migrations.AlterField(
            model_name="insectimage",
            name="species_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the species page to which this image belongs, if the insect in the image                   is identified",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insect_images",
                to="pages.speciespage",
            ),
        ),
    ]
