# Generated by Django 6.0.1 on 2026-01-21 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0012_alter_county_state_alter_gps_locality_and_more"),
        ("images", "0007_alter_insectimage_featured_family_and_more"),
        ("pages", "0002_alter_speciespage_species"),
        ("specimens", "0005_alter_specimenrecord_collecting_trip_and_more"),
        ("taxonomy", "0016_alter_family_order_alter_genus_tribe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseliveimage",
            name="collecting_trip",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the collecting trip during which the image was taken",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s",
                to="geography.collectingtrip",
            ),
        ),
        migrations.AlterField(
            model_name="baseliveimage",
            name="country",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the country in which the image was taken",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s",
                to="geography.country",
            ),
        ),
        migrations.AlterField(
            model_name="baseliveimage",
            name="county",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the county in which the image was taken",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s",
                to="geography.county",
            ),
        ),
        migrations.AlterField(
            model_name="baseliveimage",
            name="gps",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the GPS coordinates at which the image was taken",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s",
                to="geography.gps",
            ),
        ),
        migrations.AlterField(
            model_name="baseliveimage",
            name="locality",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the locality at which the image was taken",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s",
                to="geography.locality",
            ),
        ),
        migrations.AlterField(
            model_name="baseliveimage",
            name="state",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the state in which the image was taken",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="%(class)s",
                to="geography.state",
            ),
        ),
        migrations.AlterField(
            model_name="customrendition",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="renditions",
                to="images.customimage",
            ),
        ),
        migrations.AlterField(
            model_name="insectimage",
            name="species",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the species in the image, if it is identified",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="insect_images",
                to="taxonomy.species",
            ),
        ),
        migrations.AlterField(
            model_name="insectimage",
            name="species_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the species page to which this image belongs, if the insect in the image                   is identified",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="insect_images",
                to="pages.speciespage",
            ),
        ),
        migrations.AlterField(
            model_name="specimenrecordimage",
            name="usi",
            field=models.ForeignKey(
                help_text="Select the specimen in the image",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="specimen_images",
                to="specimens.specimenrecord",
            ),
        ),
    ]
